# Generated by Django 3.2 on 2021-04-15 20:38

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inout',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=16, validators=[django.core.validators.RegexValidator('Ala|ala', 'Only Ala/ala allowed')]),
            preserve_default=False,
        ),
    ]
