# Generated by Django 3.2 on 2021-04-15 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_inout_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inout',
            name='category',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('home|shopping|food|vehicles|vacation|school|communication', 'Only: home, shopping, food, vehicles, vacation, school, communication categories allowed')]),
        ),
    ]
